people:
    type:     rest
    resource: AppBundle\Controller\PeopleController

phones:
    type:     rest
    resource: AppBundle\Controller\PhonesController
    
shiporders:
    type:     rest
    resource: AppBundle\Controller\ShipordersController
    
shiptos:
    type:     rest
    resource: AppBundle\Controller\ShiptosController

items:
    type:     rest
    resource: AppBundle\Controller\ItemsController
